name: Ejecutar Selenium y Enviar Reporte

on:
  schedule:
    - cron: '0 9 * * *' 
  workflow_dispatch:      # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    environment: entorno
    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - name: Instalar dependencias
        run: |
          pip install playwright pandas openpyxl playwright-stealth
          playwright install chromium

      - name: Ejecutar Script de Selenium
        id: ejecucion
        run: |
          python Scraper_main_Carrefour.py
          echo "cuerpo_mail<<EOF" >> $GITHUB_OUTPUT
          cat texto_resultado.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Enviar Correo
        uses: dawidd6/action-send-mail@v8
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Reporte diario main Carrefour"
          to: julio_antonio_soto_vicente@carrefour.com
          from: Automatizaciones públicas Carrefour
          body: |
            La ejecución del bot de analizar las URLs de https://www.carrefour.es ha finalizado. 
            Resultado: ${{ steps.ejecucion.outputs.cuerpo_mail }}
          attachments: Resultados scraping main carrefour.xlsx